language: python
sudo: true
python:
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - sudo apt-get install python python-tk idle python-pmw python-imaging
  - sudo apt-get install -qq libegl1-mesa
  - pip install pandas
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -U scikit-learn

script:
  - nosetests Occupancy.py
