language: python
sudo: true
python:
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - sudo apt-get install python python-tk idle python-pmw python-imaging
  - sudo apt-get install -qq libegl1-mesa
  - pip install pandas
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -U scikit-learn
  - pip install Pillow
  - sudo apt-add-repository ppa:dperry/ppa-graphviz-test
  - sudo apt-get update
  - sudo apt-get autoremove graphviz
  - sudo apt-get install graphviz

script:
  - nosetests Occupancy.py
